# Generated by Django 4.1.5 on 2024-01-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
