# Generated by Django 4.0.1 on 2022-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_access_url_booking_access_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='password',
            field=models.CharField(default='UaaI0nxyT6A5MTa', max_length=15),
        ),
    ]
