# Generated by Django 4.0.1 on 2022-03-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
