# Generated by Django 4.1.5 on 2025-04-01 20:45

import booking.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False)),
                ('access_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=500)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('bookings_per_user', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('instructor', models.CharField(default='', max_length=255)),
                ('university', models.CharField(default='', max_length=255)),
                ('course', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='labs/')),
                ('description', models.CharField(default='', max_length=1000)),
                ('url', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=False)),
                ('notify_owner', models.BooleanField(default=False)),
                ('allowed_emails', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('rt', 'Real Time'), ('uc', 'Ultra Concurrent')], default='rt', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'Laboratories',
            },
        ),
        migrations.CreateModel(
            name='LaboratoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.CharField(blank=True, max_length=1500, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=booking.models.UniqueFilenameStorage(), upload_to=booking.models.generate_unique_filename_image)),
                ('video', models.FileField(blank=True, null=True, storage=booking.models.UniqueFilenameStorage(), upload_to=booking.models.generate_unique_filename_video)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('is_last', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('slot_duration', models.IntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_modification_date', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_timeframes', to='booking.equipment')),
            ],
        ),
    ]
