# Generated by Django 4.1.5 on 2025-05-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='instructor',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
