# Generated by Django 4.1.5 on 2025-06-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_laboratory_availability_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='availability_type',
            field=models.CharField(choices=[("bookable", "Available with Booking (Bookable)"),
                                            ("development", "Under Development"),
                                            ("demand", "Available on Demand (Contact Required)"),
                                            ("unavailable", "Out of Service (Maintenance/Closed)"),
                                            ("always", "Always Available (Ultraconcurrent)"),], default='development', max_length=20),
        ),
    ]
