"""
Copyright (c) Universidad Privada Boliviana (UPB) - EUBBC-Digital
MIT License - See LICENSE file in the root directory
Adriana Orellana, Angel Zenteno, Alex Villazon, Omar Ormachea
"""

# Generated by Django 4.0.1 on 2022-04-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_laboratory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
