# Generated by Django 4.1.5 on 2025-05-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_laboratory_availability_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='availability_type',
            field=models.CharField(choices=[('bookable', 'Available for Booking'), ('development', 'Under Development'), ('demand', 'Available on Demand'), ('unavailable', 'Not Available'), ('always', 'Always Available')], default='development', max_length=20),
        ),
    ]
