# Generated by Django 4.1.5 on 2025-06-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_laboratory_availability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='project_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='university_abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
