"""
Copyright (c) Universidad Privada Boliviana (UPB) - EUBBC-Digital
MIT License - See LICENSE file in the root directory
Adriana Orellana, Angel Zenteno, Alex Villazon, Omar Ormachea
"""

# Generated by Django 4.1.5 on 2023-01-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_last_modification_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
