# Generated by Django 4.1.5 on 2025-06-05 14:46

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_laboratory_project_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, storage=booking.models.UniqueFilenameStorage(), upload_to=booking.models.laboratory_image_upload_to),
        ),
    ]
