# Generated by Django 4.1.5 on 2023-02-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_kit_owner_laboratory_owner_timeframe_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='course',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='laboratories'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='instructor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='university',
            field=models.CharField(default='', max_length=255),
        ),
    ]
