# Generated by Django 4.1.5 on 2023-04-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_laboratory_course_laboratory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
