# Generated by Django 4.1.5 on 2023-06-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_kit_description_alter_laboratory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='labs/'),
        ),
    ]
