# Generated by Django 4.1.5 on 2023-12-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_laboratorycontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorycontent',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
