# Generated by Django 4.1.5 on 2024-02-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_laboratorycontent_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='notify_owner',
            field=models.BooleanField(default=False),
        ),
    ]
