# Generated by Django 4.1.5 on 2024-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_laboratory_notify_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='allowed_emails',
            field=models.TextField(blank=True, default=''),
        ),
    ]
