# Generated by Django 4.1.5 on 2024-11-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_alter_booking_equipment_alter_booking_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='type',
            field=models.CharField(choices=[('rt', 'Real Time'), ('uc', 'Ultra Concurrent')], default='rt', max_length=4),
        ),
    ]
