# Generated by Django 4.0.1 on 2022-03-29 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.laboratory')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('available', models.BooleanField(default=True)),
                ('public', models.BooleanField(default=False)),
                ('access_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.kit')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
