# Generated by Django 4.0.1 on 2022-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
