"""
Copyright (c) Universidad Privada Boliviana (UPB) - EUBBC-Digital
MIT License - See LICENSE file in the root directory
Adriana Orellana, Angel Zenteno, Alex Villazon, Omar Ormachea
"""

# Generated by Django 4.1.5 on 2023-01-27 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_kit_enabled_laboratory_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timeframe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tf_reservations', to='booking.timeframe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_reservations', to='booking.kit'),
        ),
    ]
