# Generated by Django 4.1.5 on 2023-02-06 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_timeframe_alter_booking_kit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='access_id',
            new_name='access_key',
        ),
    ]
