# Generated by Django 4.1.5 on 2023-05-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_laboratory_image'),
        ('booking', '0012_laboratory_visible_alter_laboratory_image'),
    ]

    operations = [
    ]
