# Generated by Django 4.1.5 on 2023-11-21 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_equipment_remove_booking_kit_remove_timeframe_kit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='detail_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='detail_videos/')),
                ('link', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='booking.laboratory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
