# Generated by Django 4.1.5 on 2023-11-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_laboratorycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorycontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content_photos/'),
        ),
        migrations.AlterField(
            model_name='laboratorycontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='content_videos/'),
        ),
    ]
