# Generated by Django 4.1.5 on 2023-11-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_laboratorycontent_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='laboratorycontent',
            unique_together={('laboratory', 'order')},
        ),
    ]
