# Generated by Django 4.1.5 on 2023-12-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_alter_laboratorycontent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorycontent',
            name='is_last',
            field=models.BooleanField(default=False),
        ),
    ]
