# Generated by Django 4.1.5 on 2023-07-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(default='Etc/UTC', max_length=25),
        ),
    ]
