version: "3"

services:
  db:
    image: postgres:15-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: ${RESTART_POLICY}
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - db
    restart: ${RESTART_POLICY}
volumes:
  postgres_data:
